# Generated by Django 2.2 on 2022-05-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220505_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='tag',
        ),
    ]
